newProject/config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'blogs/show'
  get 'blogs/new'
  get 'blogs/create'
  get 'blogs/edit'
  get 'blogs/update'
  get 'blogs/destroy'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'blogs#index'
  resources :users
  resources :blogs
  resources :sessions, only: %i[new create destroy]
  get 'users/create'
  get 'users/new'
  get 'users/edit'
  get 'users/show'
  get 'users/update'
  get 'users/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

newProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

newProject/app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, on: :create
  validates :content, presence: true, on: :create
  belongs_to :user
end

newProject/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, on: :create
  validates :email, presence: true, on: :create
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  has_secure_password
  validates_uniqueness_of :email
  has_many :blogs
end

newProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

newProject/app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController

  before_action :find_blog_id, only: %i[show edit destroy update]

  def index
    @blog = Blog.all
    render :index
  end

  def show
    render :show
  end

  def new
    @blog = Blog.new
    render :new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save!
      redirect_to blogs_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @blog.update_attributes(blog_params)
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def find_blog_id
    @blog = Blog.find(params[:id])
  end
end

newProject/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])

      session[:user_id] = user.id
      redirect_to blogs_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to blogs_path, notice: 'Logged out!'
  end
end

newProject/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :find_user_id, only: %i[show edit destroy update]
  # def index
  #   @user = User.all
  #   render :index
  # end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    render :show
  end

  def edit; end

  def update
    if @user.update_attributes!(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :age, :password,
                                 :password_confirmation, :bio)
  end

  def find_user_id
    @user = User.find(params[:id])
  end
end

newProject/app/helpers/application_helper.rb
module ApplicationHelper
end

newProject/app/helpers/blogs_helper.rb
module BlogsHelper
end

newProject/app/helpers/sessions_helper.rb
module SessionsHelper
end

newProject/app/helpers/users_helper.rb
module UsersHelper
end

newProject/app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

newProject/app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

newProject/app/views/blogs/edit.html.erb
<h1 class="text-muted text-center">Blogs#edit</h1>
<%= simple_form_for @blog do |f| %>
  <%= f.input :title%>
  <%= f.input :content%>
  <%= f.button :submit, class: "btn-primary"%>
<% end %>

newProject/app/views/blogs/index.html.erb
<h1 class="text-center mt-3 mb-5">BLOGS</h1>
<div class="p-3">
<% if current_user%>
  <%=link_to "Create Post", blogs_new_path, class: "h1 center " %>
  <p class="text-danger">Logged in as <%= link_to current_user.name, current_user %>.</p>
  <%=link_to "Sign Out", sessions_destroy_path, class: "h4" %>
<% else %>
  <p><%=link_to "Sign Up", users_new_path, class: 'ml-4 h4' %> | <%=link_to " Sign In", sessions_new_path, class: 'ml-4 h4' %></p>
<% end %>
</div>
<% @blog.each do |post| %>
  <div class = 'bg-success p-4 rounded-top '>
    <h2><%= link_to post.title, post, class: 'text-light'%></h2>
  </div>
  <div class="bg-dark rounded-bottom p-3">
    <small class="text-warning"><%= post.created_at %></small>
    <small class="text-danger right text-uppercase font-weight-bolder"><%= post.user.name %></small>
  </div>
  <hr>
<% end %>

newProject/app/views/blogs/new.html.erb
<h1 class="text-muted text-center">Blogs#new</h1>

<%= simple_form_for @blog do |f| %>
  <%= f.input :title, label: 'Title'%>
  <%= f.input :content, as: :text%>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

newProject/app/views/blogs/show.html.erb
<h1 class="text-center text-muted mt-3 mb-5">Blogs Detail</h1>
<div class="bg-success text-light p-3 rounded-top font-weight-bold">
  <p>Title: <%= @blog.title %></p>
  <p>Content: <%= @blog.content %></p>
</div>
<div class="bg-dark rounded-bottom p-4">
  <%= link_to "Return Home", blogs_path, class: 'text-success p-2'%>
  <% if current_user == @blog.user%>
    <%= link_to "Edit", edit_blog_path, class: 'text-success p-2'%>
    <%= link_to 'Delete',blog_path(@blog), method: :delete,data: { confirm: 'Are you sure?' }, class: 'text-success p-2' %>
  <% end %>
</div>

newProject/app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

newProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-5">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

newProject/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

newProject/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

newProject/app/views/users/edit.html.erb
<h1 class="text-muted text-center">Users#edit</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: 'Your Name please', error: 'Name is mandatory, please specify one' %>
  <%= f.input :email, placeholder: 'user@domain.com' %>
  <%= f.input :age %>
  <%= f.input :bio, as: :text%>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

newProject/app/views/users/index.html.erb
<!--<h1 class="text-center mt-3 mb-5">HOME</h1>-->

<%# @user.each do |info| %>
<!--  <div class = 'bg-success p-4 rounded-top '>-->
<!--    <h2><%#= link_to info.name, info, class: 'text-light'%></h2>-->
<!--  </div>-->
  <%# if current_user %>
<!--    <div class="bg-dark rounded-bottom p-3">-->
        <%#= link_to "Edit", edit_user_path(info), class: 'text-success p-2'%>
       <%#= link_to "Delete",info, :confirm => "Are you sure?", :method => :delete, class: 'text-success p-2'%>

<!--    </div>-->
  <%# end %>
<!--  <hr>-->
<%# end %>
<%# if current_user %>
<!--  <p class="text-danger">Logged in as <%#= current_user.name %>.</p>-->
  <%#=link_to "Sign Out", sessions_destroy_path %>
<%# else %>
<!--<p><%#=link_to "Sign Up", users_new_path, class: 'ml-4' %> | <%#=link_to " Sign In", new_session_path, class: 'ml-4' %></p>-->
<%# end %>

newProject/app/views/users/new.html.erb
<h1 class="text-muted text-center">Users#new</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: 'Your Name please', error: 'Name is mandatory, please specify one' %>
  <%= f.input :password%>
  <%= f.input :password_confirmation, error: 'Password do not match'%>
  <%= f.input :email, placeholder: 'user@domain.com' %>
  <%= f.input :age %>
  <%= f.input :bio, as: :text%>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

newProject/app/views/users/show.html.erb
<h1 class="text-center text-muted">Users show</h1>
<div class="bg-success text-light p-3 rounded-top font-weight-bold">
  <p>Name: <%= @user.name %></p>
  <p>Email: <%= @user.email %></p>
  <p>Age: <%= @user.age %></p>
  <p>Bio: <%= @user.bio %></p>
  <small class="text-warning"><%= @user.created_at %></small>
</div>
<div class="bg-dark rounded-bottom p-4">
  <%= link_to "Return Home", blogs_path, class: 'text-success p-2'%>
  <% if current_user.id == @user.id%>
    <%= link_to "Edit", edit_user_path, class: 'text-success p-2'%>
  <% end %>
</div>

newProject/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>